Adds: e2e tests for vulnerability
accurics/terrascan pull request #1009
Opened 2021-08-25 14:05 UTC by Rchanger

Adds: e2e test for fetching vulnerabilities from the registry

2021-09-03 11:02 UTC, patilpankaj212 requested changes

2021-09-03 11:02 UTC, patilpankaj212 commented on test/e2e/vulnerability/vulnerability_test.go
> +			It("should display vulnerabilities and exit with status code 0 since no violations found", func() {
code nits: we probably should name the spec as `should display vulnerabilities and scan summary` and add comment related to the exit code before the `RunScanAndVerifyVulnerabilityOutputCount` function is called.

2021-09-08 12:18 UTC, patilpankaj212 approved these changes

2021-09-16 10:44 UTC, kanchwala-yusuf approved these changes

2021-09-16 12:21 UTC, merged