Feature/endpoint policy download
accurics/terrascan pull request #1200
Opened 2022-03-25 00:10 UTC by gaurav-gogia

- add two new params `environment` and `access_token` for the config file
- download policies from authenticated endpoint
- convert policies into terrascan accepted format
- write test case for folder creation, file writing, file conversion conversion

2022-03-25 11:33 UTC, patilpankaj212 requested changes

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +		return fmt.Errorf("error reading api call response for commercial policies. error: '%v'", err)
can we change this to `fmt.Errorf("error reading response body, error: %w, err")` ?
please where `%w` to wrap errors.

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +			return err
please wrap this error

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +			return err
please wrap this error

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +		return policy, fmt.Errorf("incorrect rule argument type, must be a []byte")
you are asserting that RuleArgument is a string and logging that it must be []byte, is that correct?

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +	if !ok && templateString != "" {
if the assertion fails, do we need to the second check?

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +		return policy, fmt.Errorf("error could not unmarshal rule arguments into map[string]interface{}: '%v'", err)
can we change the message to `error occurred while unmarshaling rule arguments`.
please use `%w` for wrapping errors in all wrapped errors.

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +func getCSP(resourceType string) string {
please change the function name, `getCSP` is unclear.

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +			return fmt.Errorf("error unable to create requested directory: '%v'", err)
we should also log the `path`.
please change the error message.

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run_test.go
> +const TESTDIR = "./test_data/"
it can be "test_data"

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run_test.go
> +	policies, err := ioutil.ReadFile("./test_data/policies.json")
please use `filepath.Join()`

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run_test.go
> +func TestGetCommercialPolicy(t *testing.T) {
can we add more tests for error scenarios as well? please see tests in other packages.

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/types.go
> +package initialize
file headers

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +	const tabSpace = "    "
this is only used once

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +		return fmt.Errorf("error could not write rule metadata file on disk: '%v'", err)
we can use following error messages
`fmt.Errorf("error occurred while writing rule metedata file, %w", err)`
or 
`fmt.Errorf("could not write rule metedata file, error: %w", err)`

2022-03-25 11:33 UTC, patilpankaj212 commented on pkg/initialize/run.go
> +		return fmt.Errorf("error could not write rego code file on disk: '%v'", err)
we can use following error messages
`fmt.Errorf("error occurred while writing rego file, %w", err)`
or
`fmt.Errorf("could not write rego file, error: %w", err)`

2022-03-28 20:41 UTC, gaurav-gogia commented on pkg/initialize/run.go
> +	if res == nil {
yes, when my wifi wasn't connected and i didn't notice that it wasn't

2022-03-29 12:09 UTC, cesar-rodriguez reviewed
Can you please also update the docs here: https://github.com/accurics/runterrascan.io?

2022-03-30 12:05 UTC, patilpankaj212 approved these changes
LGTM !!

2022-03-31 10:17 UTC, merged