Removes the error generated for empty folders
accurics/terrascan pull request #1343
Opened 2022-07-27 15:16 UTC by tolidano

When scanning recursively, this should not error

Potential fix for #1323

2022-07-27 15:17 UTC, tolidano commented
I am unable to run `make cicd` locally - it sig kills during coverage checks. I expect that this should not fail, but if a test needs to be modified, I will patch.

2022-08-01 23:31 UTC, tolidano commented
@bkizer-tenable can you take a look? Thanks!

2022-08-03 16:43 UTC, tolidano commented
@tenable/terrascan-maintainers can you take a look? Thanks!

2022-08-09 02:56 UTC, tolidano commented
@cesar-rodriguez perhaps you can take a look or direct me where to go to get feedback on this?

2022-08-19 11:48 UTC, whitelancer commented
This issue is also blocking us from relying upon terrascan when we have subfolders with modules in them.  Would love to see this updated asap!

2022-08-20 03:27 UTC, tolidano commented
It’s been over 3 weeks. Is this project abandoned? Should it be forked?

2022-08-31 19:05 UTC, gaurav-gogia approved these changes

2022-09-01 18:22 UTC, gaurav-gogia requested changes
@tolidano 

Apologies for the late response. It looks like this PR is failing some unit test cases. Could you please look into them?

```
--- FAIL: TestRun (38.73s)
    --- PASS: TestRun/normal_terraform_run (0.00s)
    --- PASS: TestRun/normal_terraform_run_with_successful_output (7.81s)
    --- PASS: TestRun/terraform_run_with_--non-recursive_flag (0.00s)
    --- PASS: TestRun/normal_k8s_run (7.35s)
    --- PASS: TestRun/normal_k8s_run_with_successful_output (0.61s)
    --- PASS: TestRun/normal_k8s_run_with_successful_output_for_junit-xml_with_passed_tests (0.06s)
    --- PASS: TestRun/config-only_flag_terraform (0.00s)
    --- PASS: TestRun/iac_type_is_tfplan_and_-f_option_used_to_specify_the_tfplan.json (0.65s)
    --- PASS: TestRun/config-only_flag_k8s (0.01s)
    --- PASS: TestRun/config-only_flag_true_with_xml_output_format (0.00s)
    --- PASS: TestRun/fail_to_download_remote_repository (0.00s)
    --- PASS: TestRun/incorrect_config_file (0.00s)
    --- FAIL: TestRun/run_with_skip_rules (6.70s)
    --- FAIL: TestRun/run_with_scan_rules (8.48s)
    --- FAIL: TestRun/config_file_with_rules (7.06s)
    --- FAIL: TestRun/scan_file_with_remote_module (0.00s)
    --- PASS: TestRun/invalid_remote_type (0.00s)
    --- PASS: TestRun/valid_remote_type_with_invalid_remote_url (0.00s)
    --- PASS: TestRun/config-with-error_flag_terraform (0.00s)
```

2022-09-01 19:49 UTC, tolidano commented
Will look into this before Monday

2022-11-12 00:32 UTC, tolidano commented
So I'd like to keep working on this, but I think I'm missing something fundamental here. 
Here are two test cases that appear to be failing:
```
{
             name: "run with skip rules",
             scanOptions: &ScanOptions{
                 policyType: []string{"all"},
                 iacDirPath: runTestDir,
                 outputType: "json",
                 skipRules:  ruleSlice,
             },
         },
         {
             name: "run with scan rules",
             scanOptions: &ScanOptions{
                 policyType: []string{"all"},
                 iacDirPath: runTestDir,
                 outputType: "yaml",
                 scanRules:  ruleSlice,
             },
         },
```
But it's not clear how to understand where the "correct" output is defined or what to modify. Any tips?

2023-11-22 04:13 UTC, vdeoli-zscaler commented
Hi, is there any further update/fix on this?

2024-02-25 10:14 UTC, luboszima commented
Any updates?

2024-10-09 08:47 UTC, madpipeline commented
@tolidano did you end up using your own fork for this, since there is no response from the owners in over 2 years, and this issue seems to still not be resolved from elsewhere.

2024-10-09 11:42 UTC, tolidano commented
I think I did a much lazier thing and just ensured every folder in the tree had some small tf file in it? You can do that with a quick find -type d to get a list of folders and then ls *.tf | wc -l and check output for “0” and touch / echo a file.

2024-10-10 04:56 UTC, madpipeline commented
It is so sad that we have to resolve to solutions like this due to lack of project maintenance.
Thank you @tolidano.

2025-11-20 05:03 UTC, closed without merging