Add policy set for GitHub provider
accurics/terrascan pull request #334
Opened 2020-09-17 21:09 UTC by HorizonNet

Add GitHub as a new provider with the existing policy copied over from
the gcp policies.

Resolves #325

2020-09-17 21:11 UTC, HorizonNet commented
Tested locally via `bin/terrascan scan -t github -p pkg/policies/opa/rego/github -f repositories.tf`. Violations are shown as expected. Missing point is that violations from the original gcp policy is also reported when running `bin/terrascan scan -t github -p pkg/policies/ -f repositories.tf`.

2020-09-18 02:17 UTC, williepaul requested changes

2020-09-18 07:23 UTC, HorizonNet commented on docs/policies/github.md
> +| Identity & Access Management | gcp | MEDIUM | Repository is Not Private. | accurics.gcp.IAM.145 |
Ah, already thought that I missed this one. Updated.

2020-09-18 07:23 UTC, HorizonNet commented on pkg/policies/opa/rego/github/github_repository/accurics.github.IAM.145.json
> +    "reference_id": "accurics.github.IAM.145",
Done. Also changed the file name accordingly.

2020-09-18 07:24 UTC, HorizonNet commented on pkg/policies/opa/rego/github/github_repository/privateRepoEnabled.rego
> +    not api.config.private == true
It's in ;)

2020-09-18 07:25 UTC, HorizonNet commented
@williepaul Thanks for the feedback. Addressed your points. Let me make this one ready for review as you already gave feedback.

2020-09-18 21:46 UTC, williepaul approved these changes

2020-09-18 21:48 UTC, williepaul approved these changes
@HorizonNet all looks good, I tested the changes out locally and they worked fine. We really appreciate the contribution!

2020-09-18 21:48 UTC, merged