Added Unit test coverage for Kustomize V3 Iac-provider
accurics/terrascan pull request #399
Opened 2020-11-21 21:30 UTC by dev-gaur

Fix #379

2020-11-22 05:13 UTC, kanchwala-yusuf reviewed
I believe, there is scope for adding test cases for testing various error conditions. 
For eg: 
- In `LoadIacDir`, a test case can be added to check the error when `kustomization.yaml` is not present in the user provided directory
- Similarly, a test case for checking the error conditions when more than 1 `kustomization.yaml`s are present.
- Another, test case is possible for an empty `kustomization.yaml`


In this way some test cases can be added for `LoadKustomize` method as well

2020-11-22 16:58 UTC, dev-gaur commented
> I believe, there is scope for adding test cases for testing various error conditions.
> For eg:
> 
> * In `LoadIacDir`, a test case can be added to check the error when `kustomization.yaml` is not present in the user provided directory
Thanks for reminding. Missed that case.

> * Similarly, a test case for checking the error conditions when more than 1 `kustomization.yaml`s are present.
you can't have more than one file with the same name in a directory (as per OS constraints). So that part is taken care of already.

> * Another, test case is possible for an empty `kustomization.yaml`
Yep

2020-11-23 19:50 UTC, williepaul requested changes

2020-11-23 19:50 UTC, williepaul commented on pkg/iac-providers/kustomize/v3/load-file_test.go
> +			name:      "load iac file is not supported for helm",
"for kustomize"

2020-11-23 19:50 UTC, williepaul commented on pkg/iac-providers/kustomize/v3/load-dir.go
> +		err = errorKustomizeNotFound(errors.New("could not find a kustomization.yaml/yml file in the directory"))
Recommend to move the error definitions into a variable that can be referenced easily by unit tests

2020-11-23 19:50 UTC, williepaul commented on pkg/iac-providers/kustomize/v3/load-dir.go
> +		err = errorMultipleKustomizeFile(errors.New("a directory cannot have more than 1 kustomization.yaml/yml file"))
same--Recommend to move the error definitions into a variable that can be referenced easily by unit tests

2020-11-23 19:50 UTC, williepaul commented on pkg/iac-providers/kustomize/v3/load-dir.go
> +		err = fmt.Errorf("unable to read the kustomization file in the directory : %v", err)
Recommend to move the error definitions into a variable that can be referenced easily by unit tests

2020-12-01 23:39 UTC, williepaul approved these changes

2020-12-01 23:39 UTC, merged