Update README.md
accurics/terrascan pull request #456
Opened 2021-01-07 01:35 UTC by amirbenv

2021-01-07 15:28 UTC, dev-gaur commented on README.md
> +* Documentation: https://docs.accurics.com/projects/accurics-terrascan/en/latest/
```suggestion
* Documentation: https://docs.accurics.com/projects/accurics-terrascan
```
/en/latest is redundant.

2021-01-07 15:31 UTC, dev-gaur requested changes
one minor change requested. everything else LGTM

2021-01-08 23:36 UTC, dev-gaur requested changes

2021-01-08 23:36 UTC, dev-gaur commented on README.md
> +Please refer to our documentation to integrate with your pipeline:
IMHO, this will look better as a hyperlink.

2021-01-08 23:36 UTC, dev-gaur commented on README.md
> +Please refer to our documentation to integrate with your pipeline:
```suggestion
Please refer to our [documentation to integrate with your pipeline](https://docs.accurics.com/projects/accurics-terrascan/en/latest/cicd/)
```

2021-01-08 23:51 UTC, jlk approved these changes
LGTM

2021-01-08 23:51 UTC, merged