support for terraform registry remote modules
accurics/terrascan pull request #505
Opened 2021-01-20 11:35 UTC by patilpankaj212

1. Added remote module downloader for terraform registry
2. Fix issue - failure if the remote module itself has local modules

2021-01-22 13:42 UTC, dev-gaur requested changes

2021-01-22 13:42 UTC, dev-gaur commented on go.mod
> +	github.com/hashicorp/go-getter v1.5.2
@patilpankaj212 can you omit this go.mod change ? This caused build failure on ARM and willie's PR undid this. 
https://github.com/accurics/terrascan/pull/507/files

2021-01-22 17:12 UTC, kanchwala-yusuf approved these changes

2021-01-22 17:15 UTC, merged

2021-02-26 22:34 UTC, jlunaq commented
Hi there,

Are the remote modules only downloadable from the official terraform registry? I need to download some modules from my private repos but it tries to read them locally.

2021-02-27 16:44 UTC, patilpankaj212 commented
Hello @jlunaq,
We remote backends - git, s3, gcs, http, terraform-registry
Could you please let us know where you have hosted your repo?
Can you please give an example of the source attribute in your module definition?

2021-03-04 20:13 UTC, jlunaq commented
Hi @patilpankaj212 ,

Sorry for the late response, I haven't been notified.
The repo is in github, I found that terrascan is able to read the module when it is in the root directory.
So this issue is more related to the modules which are in a subdirectory, like this:

`source = "git@github.com:company/module.git//modules/base?ref=v2.0.0"`

In this case is where I'm getting the error

`<nil>: Failed to read module directory; Module directory /Users/jluna/my-project/git@github.com:company/module.git/modules/roles does not exist or cannot be read.`

2021-03-06 06:48 UTC, patilpankaj212 commented
Hello @jlunaq,
Thanks for doing the tests. Looks like a defect to me. Can you please open a issue for this case?

2021-03-09 17:56 UTC, jlunaq commented
Sure, will do

2021-03-09 18:02 UTC, jlunaq commented
https://github.com/accurics/terrascan/issues/600

2021-03-10 06:38 UTC, patilpankaj212 commented
Thanks @jlunaq