Check for nil decoder before use
accurics/terrascan pull request #612
Opened 2021-03-10 18:49 UTC by jlk

simple add of if test before using decoder.

2021-03-11 01:43 UTC, patilpankaj212 commented on pkg/utils/yaml.go
> +	if dec == nil {
Though the nil check is good, looking at the yaml.NewDecoder method, it will either panic or return a non nil decoder.

2021-03-11 01:46 UTC, patilpankaj212 reviewed
added review.

2021-03-20 18:31 UTC, dev-gaur commented
I think the CI will pass here even if you don't include the changes in go.mod and go.sum . I understand that running `make validate` locally must have required a `go mod vendor` first.

2021-03-23 04:08 UTC, dev-gaur commented on pkg/utils/yaml.go
> +		err := fmt.Errorf("error cretaing yaml decoder in ScanIacDocumentsFromYaml()")
hey @jlk , I think the user wouldn't care to know the function name here. so we can keep the error message generic and simple. also, creating is mispelled

2021-03-23 04:08 UTC, dev-gaur requested changes

2021-03-23 04:08 UTC, dev-gaur commented on pkg/utils/yaml.go
> +		err := fmt.Errorf("error cretaing yaml decoder in ScanIacDocumentsFromYaml()")
requsting this change

2021-04-01 01:32 UTC, jlk commented
Sorry for ignoring this. Upon looking closer, the issue was in the library we're using, so will open a PR with them. Closing this PR.

2021-04-01 01:32 UTC, closed without merging

2021-04-05 08:06 UTC, dev-gaur commented
#611