Adding release checklist
accurics/terrascan pull request #734
Opened 2021-05-05 05:00 UTC by jlk

Initial PR for a release checklist.

Creating PR now to get feedback - let me know any thoughts, or feel free to contribute.

I know this is missing integration testing - if somebody's bored, feel free to add, otherwise I'll get that in soon.

2021-05-05 14:27 UTC, dev-gaur requested changes
minor changes requested. thanks for the initiative.

2021-05-05 14:27 UTC, dev-gaur commented on release_checklist.md
> +make test
```suggestion
make cicd
```

2021-05-05 14:27 UTC, dev-gaur commented on release_checklist.md
> +make test
this will also test the docker build.

2021-05-05 14:27 UTC, dev-gaur commented on release_checklist.md
> +make test
And in future we can add subtargets like `acceptance tests` and `e2e-tests` under the make `cicd` target

2021-05-05 14:27 UTC, dev-gaur commented on release_checklist.md
> +(again, subsitute v1.5.0 for the appropriate version being released)
Maybe put this NOTICE above the code block ? 😅 or use a place holder like <NEW_TERRASCAN_VERSION> instead of v1.5.0 .

2021-05-06 08:37 UTC, dev-gaur approved these changes

2021-05-06 08:37 UTC, merged

2021-05-06 12:05 UTC, kanchwala-yusuf commented
Thank you @jlk for this PR!