Dockerfile support
accurics/terrascan pull request #849
Opened 2021-06-09 11:01 UTC by Rchanger

Adds: Docker as an IaC Provider.

-  Scan support for Dockerfile.
-  Support In file skip rules and resource prioritizing. 

Result of scan with test policies.
```CMD
 % ./bin/terrascan scan -d integrations/atlantis -i docker -p /Users/suvarna/Desktop/docker  -o json
{
  "results": {
    "violations": [
      {
        "rule_name": "add",
        "description": "Use Copy instead of Add",
        "rule_id": "docker.Medium.0001",
        "severity": "MEDIUM",
        "category": "Security",
        "resource_name": "Dockerfile",
        "resource_type": "dockerfile",
        "file": "Dockerfile",
        "line": 1
      }
    ],
    "skipped_violations": null,
    "scan_summary": {
      "file/folder": "/Users/suvarna/go/src/github.com/rchanger/terrascan/integrations/atlantis",
      "iac_type": "docker",
      "scanned_at": "2021-06-09 10:56:10.947269 +0000 UTC",
      "policies_validated": 2,
      "violated_policies": 1,
      "low": 0,
      "medium": 1,
      "high": 0
    }
  }
}
```

2021-06-22 12:18 UTC, dev-gaur submitted a review, later dismissed
Please add a testfile demonstrating scan of a Dockerfile that includes multi-staging build 

https://docs.docker.com/develop/develop-images/multistage-build/

2021-06-22 12:18 UTC, dev-gaur commented on pkg/iac-providers/docker/v1/load-dir.go
> +	for fileDir, files := range fileMap {
Can you try re-writing this using DRY principle? like, re-using LoadIacFile function here? You can get a reference from the k8s iac-provider implementation.

2021-07-01 11:43 UTC, kanchwala-yusuf reviewed
It is a request to be generous with comments. Ideally, a new contributor should be able to understand the code only from the comments.

2021-07-01 11:43 UTC, kanchwala-yusuf commented on pkg/iac-providers/docker/v1/load-file.go
> +		zap.S().Errorf("error while parsing file %s", absFilePath, err)
it would be better to use `Dockerfile` instead of `file`

2021-07-01 11:43 UTC, kanchwala-yusuf commented on pkg/iac-providers/docker/v1/parser.go
> +	config := []ResourceConfig{}
Oh! I got confused between this `ResourceConfig` and `output.ResourceConfig`

2021-07-01 11:43 UTC, kanchwala-yusuf commented on pkg/iac-providers/docker/v1/testdata/file-test-data/valid-Dockerfile
> +FROM runatlantis/atlantis:v0.16.1
Would it be possible to add `minSeverity`, `maxSeverity` and `skipRules` in one of the Dockerfiles for testing

2021-07-01 15:21 UTC, kanchwala-yusuf approved these changes

2021-08-02 03:12 UTC, cesar-rodriguez requested changes
Can we add a warning for when you specify the `-i docker` flag and no Dockerfiles were found?

2021-08-02 17:48 UTC, Rchanger commented
> Can we add a warning for when you specify the `-i docker` flag and no Dockerfiles were found?

Yes, added changes for warning

2021-08-02 23:17 UTC, cesar-rodriguez approved these changes

2021-08-03 08:57 UTC, Rchanger commented
> Please add a testfile demonstrating scan of a Dockerfile that includes multi-staging build
> 
> https://docs.docker.com/develop/develop-images/multistage-build/

This test case has been pushed, you can review that 
Thanks

2021-08-03 14:27 UTC, kanchwala-yusuf approved these changes

2021-08-03 17:07 UTC, patilpankaj212 approved these changes

2021-08-04 02:58 UTC, merged