Initial support for image scanning
accurics/terrascan pull request #989
Opened 2021-08-13 16:50 UTC by Rchanger

Initial support for image scanning

2021-08-17 08:53 UTC, patilpankaj212 commented on pkg/iac-providers/output/vulnerability.go
> +	Two0   ACRCvssBase `json:"2.0"`
can these fields changed to `V2` and `V3`?

2021-08-17 08:53 UTC, patilpankaj212 commented on pkg/iac-providers/output/vulnerability.go
> +//ACRCvssBase ...
please add a description for the struct.

2021-08-17 08:53 UTC, patilpankaj212 commented on pkg/runtime/executor.go
> +	return res
can be modified to `return e.vulnerabilityEngine.FindVulnerabilities(results.ResourceConfig, options)`

2021-08-17 08:53 UTC, patilpankaj212 commented on pkg/iac-providers/output/types.go
> +	Vulnerabilities []Vulnerability `json:"vulnerabilities"`
should the struct's name be changed as it now contain additional field? eg: `ContainerDetails` ?

2021-08-19 09:54 UTC, patilpankaj212 submitted a review, later dismissed
LGTM !!

2021-08-19 12:58 UTC, cesar-rodriguez requested changes
Can you please fix merge conflicts?

2021-08-20 02:52 UTC, cesar-rodriguez requested changes
Can you please update the readme and usage docs with instructions for the new `--find-vuln` flag?

2021-08-20 06:53 UTC, Rchanger commented
> Can you please update the readme and usage docs with instructions for the new `--find-vuln` flag?

updated  readme and usage docs

2021-08-22 18:46 UTC, cesar-rodriguez approved these changes

2021-08-22 18:47 UTC, merged