update resource type to map[string]bool
accurics/terrascan pull request #992
Opened 2021-08-16 07:00 UTC by patilpankaj212

1. changed `resource` type in metadata json from `string` to `map[string]bool` and made related changes in resource type filter specification.
2. marked a few e2e tests pending.

**pending** - add more items in resource types of a metadata json if applicable.

2021-08-19 05:13 UTC, harkirat22 approved these changes
LGTM (Checked policies part)

2021-08-19 10:27 UTC, Rchanger approved these changes
LGTM

2021-08-19 12:57 UTC, cesar-rodriguez requested changes
Can you please fix merge conflicts?

2021-08-20 01:26 UTC, cesar-rodriguez approved these changes

2021-08-20 01:27 UTC, merged